---
title: "Chilkat_Harvest_2000"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chilkat_Harvest_2000}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cwtr)
```



```{r example1, fig.height = 5, fig.width = 6}
#Point Estimates for Troll, SW 28, NW Quadrant
x <- cwtEst(N=c(33666,NA), n=7618, lambda=c(138,140,116,116), m=1, theta=c(0.01886,102.15))
#Use the print method to look at results
x
#Use the summary method to obtain SE, CV, and CI
summary(x)
#Bootstrap Estimates
xBoot <- cwtBoot(x, method="parametric", nreps=10000)
#Use the print method again to look at results
xBoot
#Use the summary method again to obtain SE, CV, and CI
summary(xBoot)
#Use the plot method to obtain plots of the bootstrap simulation
plot(xBoot)
```



```{r example2, fig.height = 4, fig.width = 6}
#Point Estimates for Troll, SW 30, NW Quadrant
x <- cwtEst(N=c(124896,NA), n=35159, lambda=c(783,798,633,633), m=6, theta=c(0.018867925,102.145455))
#Use the print method to look at results
x
#Use the summary method to obtain SE, CV, and CI
summary(x)
#Bootstrap Estimates
xBoot <- cwtBoot(x, method="parametric", nreps=10000)
#Use the print method again to look at results
xBoot
#Use the summary method again to obtain SE, CV, and CI
summary(xBoot)
#Use the plot method to obtain plots of the bootstrap simulation
plot(xBoot)
```


```{r example3, fig.height = 4, fig.width = 6 }
#Point Estimates for Sport, SW 34, NE Quadrant
x <- cwtEst(N=c(6056,3210960), n=2008, lambda=c(109,112,97,97), m=2, theta=c(0.018867925,102.145455))
#Use the print method to look at results
x
#Use the summary method to obtain SE, CV, and CI
summary(x)
#Bootstrap Estimates
xBoot <- cwtBoot(x, method="parametric", nreps=10000)
#Use the print method again to look at results
xBoot
#Use the summary method again to obtain SE, CV, and CI
summary(xBoot)
#Use the plot method to obtain plots of the bootstrap simulation
plot(xBoot)
```