---
title: "CWTexample_Geiger1990"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CWTexample_Geiger1990}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cwtr)
```



```{r}
#Point Estimates for Geiger's first example
x <- cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=10, theta=c(0.5,NA))
#Use the print method to compare results
x
#Summary statistics from the equations
summary(x, alpha=0.2)
#Calculate the simulated distribution
xBoot <- cwtBoot(x, method="geiger", nreps=10000)
#Use the print method to see results
xBoot
#Summary statistics from the Bootstrap method
summary(xBoot, alpha=0.2)
#Figure 1
hist(xBoot$Bootstrap$r.boot, xlim = c(0,200)); abline(v=100, lwd=3, col="red")

#Point Estimates for Geiger's 'P Known' example
x8  = cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=8 , theta=c(0.5,NA))
x12 = cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=12, theta=c(0.5,NA))
x15 = cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=15, theta=c(0.5,NA))
#Bootstrap Estimates
xBoot8  <- cwtBoot(x8 , method="geiger", nreps=10000)
xBoot12 <- cwtBoot(x12, method="geiger", nreps=10000)
xBoot15 <- cwtBoot(x15, method="geiger", nreps=10000)
#Figure 2
par(mfrow=c(3,1))
hist(xBoot8$Bootstrap$r.boot , xlim = c(0,300), main="2a"); abline(v=80,  lwd=3, col="red")
hist(xBoot12$Bootstrap$r.boot, xlim = c(0,300), main="2b"); abline(v=120, lwd=3, col="red")
hist(xBoot15$Bootstrap$r.boot, xlim = c(0,300), main="2c"); abline(v=150, lwd=3, col="red")

#
varbinom <- function(p, n) { return( p*(1-p)/(n-1)) }
sqrt(varbinom(  5/10,  10))
sqrt(varbinom( 25/50,  50))
sqrt(varbinom(50/100, 100))

#Point Estimates for Geiger's 'P is Estimated' example
x    <- cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=10, theta=c(0.5,NA))
x10  <- cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=10, theta=c(0.5,0.167))
x50  <- cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=10, theta=c(0.5,0.071))
x100 <- cwtEst(N=c(1000,NA), n=200, lambda=c(1,1,1,1), m=10, theta=c(0.5,0.050))
#Summary statistics 
summary(x   , alpha=0.2)
summary(x10 , alpha=0.2)
summary(x50 , alpha=0.2)
summary(x100, alpha=0.2)
#"Hack" the cwt object to reproduce the P estimated example in geiger
x10$InputData$theta[2]  = 10
x50$InputData$theta[2]  = 50
x100$InputData$theta[2] = 100
#Bootstrap Estimates
xBoot    <- cwtBoot(x   , method="geiger", nreps=1000)
xBoot10  <- cwtBoot(x10 , method="geiger", nreps=1000)
xBoot50  <- cwtBoot(x50 , method="geiger", nreps=1000)
xBoot100 <- cwtBoot(x100, method="geiger", nreps=1000)
#Summary statistics
summary(xBoot   , alpha=0.1)
summary(xBoot10 , alpha=0.1)
summary(xBoot50 , alpha=0.2)
summary(xBoot100, alpha=0.2)
#Figure 3
par(mfrow=c(3,1))
hist(xBoot10$Bootstrap$r.boot , xlim = c(0,300), main="3a"); abline(v=100, lwd=3, col="red")
hist(xBoot50$Bootstrap$r.boot , xlim = c(0,300), main="3b"); abline(v=100, lwd=3, col="red")
hist(xBoot100$Bootstrap$r.boot, xlim = c(0,300), main="3c"); abline(v=100, lwd=3, col="red")



##############
x <- cwtEst(N=c(124896,NA), n=35159, lambda=c(783,798,633,633), m=6, theta=c(0.018867925,102.145455))
xBoot <- cwtBoot(x, method="parametric", nreps=10000)
summary(xBoot)
plot(xBoot)



print(xBoot)




```

